### ISSUE TITLE
Cupertiono Page / IOS Back swipe support

### ISSUE THREAD

**Issue by Clon1998** [arthurbcd/go_transitions#2]
Hey,
awesome package and also a really clean API to use!

I noticed that the only thing missing is the "Swipe Back" function of IOS that triggers a back action.

By default flutter will add that if I am using a `CupertinoPage` via the `CupertinoPageTransitionsBuilder` and the back action/observer is added via the classes private class `_CupertinoBackGestureDetector`.

Edit: I have tried the `.cupertino` and `.theme` which both do not behave the same way as the normal `CupertinoPage`. This is actually really surprising given the fact that the two customizable actually extend `MaterialPage`/`CupertinoPage`

https://github.com/user-attachments/assets/52ba9bde-b378-437d-8f0d-2eecfafd7847

**Comment by Clon1998** [comment]
I was able to locate the issue.
Based on this [answer](https://stackoverflow.com/questions/75412087/flutter-enable-swipe-back-on-custom-transition-fadeanimation) I looked at the current implementation.
It seems like the primary problem is that `GoCupertinoPageRoute` is using the mixin `GoPageRoute` which does not invoke the `buildTransitions` of the parent `CupertinoPageRoute ` to get the active stack with the `_CupertinoBackGestureDetector`

**Comment by arthurbcd** [comment]
Hey @Clon1998 !

Thanks for the feedback and also for the investigation, that's very helpful. 

I'm absolutely looking into it :).

**Comment by arthurbcd** [comment]
The GoCupertinoPage implementation seems fine, the `buildPageTransitions` with the back-swipe support is there in the super.build default parameter.

```dart
  const GoCupertinoPage({
    this.title,
    super.builder = CupertinoRouteTransitionMixin.buildPageTransitions<dynamic>,
    super.style,
    super.settings,
    super.child,
  });
```

The problem was being caused by this:

```dart
  if (!animation.isAnimating && !secondaryAnimation.isAnimating) return child;
```

I added this to improve performance is case of no animations. But CupertinoPage needs to have the widget tree untouched as it has an active gesture detector to listen to back swipes. So it was losing its state.

I removed this, so now the widget tree will stay the same and any PageRoute states won't be lost.

Now it's working again, but note that applying a non-linear `GoTransitionStyle.curve` also changes the back-swipe animation, which is kinda funny btw. :)

Bump your version to `0.5.3`.

Thanks a lot @Clon1998, have a nice day !

**Comment by Clon1998** [comment]
> The GoCupertinoPage implementation seems fine, the `buildPageTransitions` with the back-swipe support is there in the super.build default parameter.
> 
> 
> 
> ```dart
> 
>   const GoCupertinoPage({
> 
>     this.title,
> 
>     super.builder = CupertinoRouteTransitionMixin.buildPageTransitions<dynamic>,
> 
>     super.style,
> 
>     super.settings,
> 
>     super.child,
> 
>   });
> 
> ```
> 
> 
> 
> The problem was being caused by this:
> 
> 
> 
> ```dart
> 
>   if (!animation.isAnimating && !secondaryAnimation.isAnimating) return child;
> 
> ```
> 
> 
> 
> I added this to improve performance is case of no animations. But CupertinoPage needs to have the widget tree untouched as it has an active gesture detector to listen to back swipes. So it was losing its state.
> 
> 
> 
> I removed this, so now the widget tree will stay the same and any PageRoute states won't be lost.
> 
> 
> 
> Now it's working again, but note that applying a non-linear `GoTransitionStyle.curve` also changes the back-swipe animation, which is kinda funny btw. :)
> 
> 
> 
> Bump your version to `0.5.3`.
> 
> 
> 
> Thanks a lot @Clon1998, have a nice day !

Awesome! Thanks for your quick work.
I just wonder if we could add a modifier to add the back gesture to all of the other animations besides Cupertino/Theme.

**Comment by arthurbcd** [comment]
Done! https://pub.dev/packages/go_transitions

Really cool suggestion btw! It will reverse the current route transition.

**Comment by Clon1998** [comment]
Awesome! Thanks a ton. Works really great :)
